In [1]:
import numpy as np
from scipy.spatial.transform import Rotation as R

In [2]:
def norm(vec):
    vec = np.array(vec)
    norm_vec = vec / np.sqrt(sum(vec**2))
    return norm_vec


def quaternion_to_axis_angle(q):
    """
    transform quaternion to axis angel representation

    Params:
        q: quaternion with x, y, z, w
    Return:
        [axis_x, axis_y, axis_z, angle]
    """
    # the quaternion is x, y, z, w
    axis_angle = np.zeros(4)
    axis_angle[3] = 2 * np.arccos(q[3])
    sin_half_theta = np.sqrt(1.0 - q[3]**2)
    axis_angle[0] = q[0] / sin_half_theta
    axis_angle[1] = q[1] / sin_half_theta
    axis_angle[2] = q[2] / sin_half_theta

    # vector normalization
    axis_angle[:3] = norm(axis_angle[:3])
    return axis_angle


def axis_angle_to_euler_vector(axis_angle):
    """
    axis angle to euler vector, [theta * v_x, theta * v_y, theta * v_z]
    """
    euler_vector = axis_angle[:3] * axis_angle[3]
    return euler_vector


def euler_vector_to_axis_angle(euler_vector):
    """
    euler vector back to axis angle
    """
    axis_angle = np.zeros(4)
    axis_angle[3] = np.sqrt(np.sum(np.power(euler_vector, 2)))
    axis_angle[:3] = euler_vector / axis_angle[3]
    return axis_angle

In [16]:
# theta = 180, because cos(theta/2) = 0
# axis = (.5, .5, 0), after normalization (sqrt(2)/2, sqrt(2)/2, 0)
key_rots = R.random(5, random_state=2342345)

q = key_rots.as_quat()[4]
r = R.from_quat(q)

### scipy implementation

In [17]:
r.as_rotvec()

array([-1.77541425,  0.23931706, -1.52603794])

In [21]:
np.sqrt(sum(r.as_rotvec()**2))

2.3533296023257484

### Own implementation

In [18]:
axis_angle = quaternion_to_axis_angle(q)
euler_vec = axis_angle_to_euler_vector(axis_angle)
euler_vec

array([ 2.96478735, -0.39963867,  2.5483506 ])

In [19]:
axis_angle

array([ 0.75442652, -0.10169296,  0.64845908,  3.9298557 ])